apiVersion: v1
kind: Secret
metadata:
  name: paymentservice-secrets
type: Opaque
data:
  ReviewsDbConnectionString: QWNjb3VudEVuZHBvaW50PWh0dHBzOi8vcmV2aWV3c2RiYWNjb3VudDEyMy5kb2N1bWVudHMuYXp1cmUuY29tOjQ0My87QWNjb3VudEtleT1kRG1mOGFqa1RYTnhKQjg1SnFOOGtNWFBTMnVtc2ZMeXdXSm1Xb1plQ09iTWlWQjBxVERxTEg3Y2x3Y3FQN21zS2hmamF3dzU2MWc5QUNEYlRRY1lCQT09Ow==
  CartDbConnectionString: QWNjb3VudEVuZHBvaW50PWh0dHBzOi8vYWRkdG9jYXJzZXJ2ZXJsZXNzLmRvY3VtZW50cy5henVyZS5jb206NDQzLztBY2NvdW50S2V5PWVtbWRKT1hnaHA5eWsxWmJsaUlkQ1BRU2RtQWFMM3NBR3J1VTc4RmNwaTI1WFFnT01zVnNobjN5NlZYOU5DR3lzYVJPWkVUaG5nWVRBQ0RialNHc1RBPT07