name: CI/CD - Authentication Service

on:
  push:
    paths:
      - "microservices/authenticationservice/**"
      - "kubernetes/**"
      - ".github/workflows/authentication-service.yml"

env:
  AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
  AZURE_ACR_NAME: ${{ vars.AZURE_ACR_NAME }}
  AKS_CLUSTER_NAME: ${{ vars.AKS_CLUSTER_NAME }}
  SERVICE_NAME: "AuthenticationService"
  SERVICE_NAME_LOWER: "authenticationservice"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and tag Docker image
        run: |
          docker build \
            -t ${{ env.AZURE_ACR_NAME }}.azurecr.io/${{ env.SERVICE_NAME_LOWER }}:${{ github.sha }} \
            -f ./microservices/${{ env.SERVICE_NAME_LOWER }}/Dockerfile \
            .

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ env.AZURE_ACR_NAME }}

      - name: Push Docker image to ACR
        run: docker push ${{ env.AZURE_ACR_NAME }}.azurecr.io/${{ env.SERVICE_NAME_LOWER }}:${{ github.sha }}

      - name: Set AKS context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Deploy to AKS
        run: |
          # Actualizar la imagen en el deployment
          kubectl set image deployment/${{ env.SERVICE_NAME_LOWER }} \
            ${{ env.SERVICE_NAME_LOWER }}=${{ env.AZURE_ACR_NAME }}.azurecr.io/${{ env.SERVICE_NAME_LOWER }}:${{ github.sha }} \
            || kubectl apply -f ./kubernetes/${{ env.SERVICE_NAME_LOWER }}-deployment.yaml
          
          kubectl apply -f ./kubernetes/${{ env.SERVICE_NAME_LOWER }}-service.yaml
          
          # Verificar el deployment
          kubectl rollout status deployment/${{ env.SERVICE_NAME_LOWER }} --timeout=300s