name: CI/CD - Authentication Service

on:
  push:

env:
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AZURE_ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}
  AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
  SERVICE_NAME: "authenticationservice"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules if any)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: List microservice folder files explicitly
        run: ls -la ${{ github.workspace }}/microservices/${{ env.SERVICE_NAME }}

      - name: Confirm Dockerfile presence
        run: test -f ${{ github.workspace }}/microservices/${{ env.SERVICE_NAME }}/Dockerfile && echo "Dockerfile existe" || echo "Dockerfile NO existe"

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}", "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}", "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Build and tag Docker image (simple test)
        run: |
          cd ${{ github.workspace }}/microservices/${{ env.SERVICE_NAME }}
          docker build -f Dockerfile .

      - name: Build and tag Docker image (full)
        run: |
          cd ${{ github.workspace }}/microservices/${{ env.SERVICE_NAME }}
          docker build -t ${{ env.AZURE_ACR_NAME }}.azurecr.io/${{ env.SERVICE_NAME }}:${{ github.sha }} -f Dockerfile .

      - name: Docker login
        run: docker login ${{ env.AZURE_ACR_NAME }}.azurecr.io -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Push Docker image to ACR
        run: docker push ${{ env.AZURE_ACR_NAME }}.azurecr.io/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Set AKS credentials
        uses: azure/aks-set-context@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}", "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}", "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Deploy to AKS
        run: |
          kubectl apply -f ./kubernetes/authenticationservice-deployment.yaml
          kubectl apply -f ./kubernetes/authenticationservice-service.yaml
