name: CI/CD - Payment Service

on:
  push:
    branches:
      - main
    paths:
      - "microservices/paymentservice/**"
      - "kubernetes/**"
      - ".github/workflows/payment-service.yml"

env:
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AZURE_ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}
  AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
  SERVICE_NAME: "paymentservice"
  SERVICE_NAME_LOWER: "paymentservice"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}", "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}", "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Build and tag Docker image
      run: |
        docker build --platform linux/amd64 \
          -t ${{ env.AZURE_ACR_NAME }}.azurecr.io/${{ env.SERVICE_NAME_LOWER }}:${{ github.sha }} \
          -f ./microservices/${{ env.SERVICE_NAME_LOWER }}/Dockerfile \
          ./microservices/${{ env.SERVICE_NAME_LOWER }}

    - name: Docker login
      run: docker login ${{ env.AZURE_ACR_NAME }}.azurecr.io -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Push Docker image to ACR
      run: docker push ${{ env.AZURE_ACR_NAME }}.azurecr.io/${{ env.SERVICE_NAME_LOWER }}:${{ github.sha }}

    - name: Set AKS credentials
      uses: azure/aks-set-context@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}", "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}", "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
        resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
        cluster-name: ${{ env.AKS_CLUSTER_NAME }}

    - name: Deploy to AKS
      run: |
        # Reemplaza el tag de la imagen en el YAML del despliegue con el SHA del commit.
        sed -i 's|${{ env.AZURE_ACR_NAME }}.azurecr.io/${{ env.SERVICE_NAME_LOWER }}:vR|${{ env.AZURE_ACR_NAME }}.azurecr.io/${{ env.SERVICE_NAME_LOWER }}:${{ github.sha }}|g' ./kubernetes/${{ env.SERVICE_NAME_LOWER }}-deployment.yaml
        
        # Aplica los cambios completos al despliegue, incluyendo las variables de entorno.
        kubectl apply -f ./kubernetes/${{ env.SERVICE_NAME_LOWER }}-deployment.yaml
        
        # Aplica los cambios al servicio (si es necesario).
        kubectl apply -f ./kubernetes/${{ env.SERVICE_NAME_LOWER }}-service.yaml
